
#' Title
#'
#' @param .x 
#' @param ... 
#'
#' @return
#' @export
#'
#' @examples
summary_measures <- function(.x, ...) {
  .x %>% 
    mutate(claim_amount_all = select(., starts_with("claim_amount")) %>% rowSums,
           claim_count_all = select(., starts_with("claim_count")) %>% rowSums) %>% 
    group_by(!!!quos(...)) %>% 
    summarise(
      exposure = sum(exposure),
      premium = sum(premium),
      claim_amount_total = sum(claim_amount_all),
      claim_count_total = sum(claim_count_all)) %>% 
    mutate(
      pure_premium = claim_amount_total / exposure,
      average_premium = premium / exposure,
      frequency = claim_count_total / exposure,
      severity = claim_amount_total / claim_count_total,
      loss_ratio = claim_amount_total / premium)
}

#' Title
#'
#' @param .x 
#' @param .target 
#' @param .measure 
#'
#' @return
#' @export
#'
#' @examples
plot_measure <- function(.x, .target, .measure) {
  targ <- enquo(.target)
  meas <- enquo(.measure)
  .x %>% 
    summarise_stats(!!targ) %>% 
    ggplot() + 
    aes(x = fct_reorder(!!targ, !!meas), 
        y = !!meas) + 
    xlab(quo_name(targ)) + 
    geom_point(size = rel(3)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
}

#' Title
#'
#' @param .tbl 
#' @param .vars 
#' @param .measure 
#' @param ... 
#'
#' @return
#' @export
#'
#' @examples
plot_measure_at <- function(.tbl, .vars, .measure, ...) {
  vars <- dplyr:::tbl_at_vars(.tbl, .vars, .include_group_vars = TRUE)
  vars_syms <- dplyr:::vars_select_syms(vars = vars, funs = NULL, tbl = .tbl)
  
  vars_syms %>%
    map(~plot_measure(.tbl, !!., !!enquo(.measure))) %>% 
    purrr::lift_dl(gridExtra::grid.arrange)(., ...)
}


#' Rebase columns 
#' 
#' @description This function will rebase the data by dividing each numeric 
#' column by the reference level
#' 
#' The reference column is never rebased.
#' 
#' @param .tbl a `tbl` object
#' @param .var a column name
#' @param level the level in `.var` which should decide the baseline for each numeric field
#' @param .excludes A list of columns generated by `vars()`, a character vector 
#' of column names, a numeric vector of column positions, or `NULL`
#'
#' @return An object of the same class as `.tbl`
#' @export
#'
#' @examples
rebase_to <- function(.tbl, .var, level, .excludes = NULL) {
  var <- enquo(.var)
  
  excludes <- dplyr:::tbl_at_vars(.tbl, .excludes, .include_group_vars = TRUE)
  excludes_syms <- dplyr:::vars_select_syms(excludes, NULL, .tbl) %>% map(sym)
  excludes <- map(excludes_syms, function(s) expr(-!!s))
  
  index <- which(pull(.tbl, !!var) == level)
  
  if(length(index) == 0) 
    stop(glue::glue('{level} was not found in the column {quo_name(var)}'), 
         call. = F)
  
  if(length(index) > 1 ) {
    warning("{multiple instances of level} in the column {quo_name(var)}")
    index <- index[[1]]
  }
  
  .tbl %>% 
    mutate_at(.vars =  vars(which(map_lgl(., is.numeric)), 
                            !!!quos(!!!excludes_syms),
                            -!!var),
              .funs = funs(. / .[[index]]))
}

# Example

risks_table_agg %>% 
  plot_measure_at(vars(sex, age_range, vehicle_category), 
                  loss_ratio, 
                  ncol = 2)  

risks_table_agg %>% 
  summary_measures(sex) %>% 
  rebase_to(sex, "female")
  
